[build]
command = "hugo --gc --minify"
publish = "public"
[build.environment]
HUGO_THEME = "educenter"
HUGO_VERSION = "0.84.1"
[menu.main]
URL = "career"
name = "Our Vacancies"
parent = "About"
weight = 3
